In [44]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import title

In [45]:
data = pd.read_csv(r'C:\Users\FARHAD\PycharmProjects\GithubCV\recommandation_systems_TMDB\Data\clean_data.csv')

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4803 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  release_date          4802 non-null   object
 11  revenue               4803 non-null   int64
 12  runtime               4801 non-null   float64
 13  spoken_languages      4803 non-null   object
 14  tagline               3959 non-null   object
 15  vote_average          4803 non-null   float64
 16  vote_count            4803 non-null   int64
 17  cast                  4803 non-null   object
 18  crew                  4803 non-null   object
dtypes: float64(3), int64(5), object(11)
memory usage: 713.1+ KB

In [47]:
data['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [48]:
data['overview'].isnull().sum()

np.int64(3)

In [49]:
data['overview'] = data['overview'].fillna('')

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [51]:
tfv = TfidfVectorizer(min_df=3, max_features=None, ngram_range=(1, 3), stop_words='english')

In [52]:
tfv_matrix = tfv.fit_transform(data['overview'])
tfv_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 121480 stored elements and shape (4803, 9919)>

In [53]:
# getting TF-IDF matrix of first entry of overview..
# Return a array representation
tfv_matrix.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [54]:
# lets transpose matrix
tfv_matrix[0].T.toarray()

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [55]:
X = tfv_matrix.toarray()

In [56]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,9909,9910,9911,9912,9913,9914,9915,9916,9917,9918
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [58]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [59]:
sig[0]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [60]:
index = data.index
index

RangeIndex(start=0, stop=4803, step=1)

In [61]:
title = data['original_title']

In [62]:
title[4802]

'My Date with Drew'

In [63]:
indices = pd.Series(data.index, index=data['original_title'])
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [64]:
#sort similarity values in ascending order

sigma_scores=sorted(list(enumerate(list(sig[indices['Avatar']]))),key=lambda x:x[1],reverse=True)
sigma_scores

[(0, np.float64(0.76163649309625)),
 (1341, np.float64(0.7616030155858681)),
 (634, np.float64(0.7616028561141562)),
 (3604, np.float64(0.761601930611584)),
 (2130, np.float64(0.7616015339622925)),
 (775, np.float64(0.7616011086528326)),
 (529, np.float64(0.7615996114069044)),
 (151, np.float64(0.7615991171152051)),
 (311, np.float64(0.7615990624497703)),
 (847, np.float64(0.7615987706430224)),
 (570, np.float64(0.7615986450599548)),
 (942, np.float64(0.7615984376900236)),
 (36, np.float64(0.761597988130195)),
 (1610, np.float64(0.7615979793934843)),
 (3070, np.float64(0.7615978406764746)),
 (1033, np.float64(0.7615978182403835)),
 (2628, np.float64(0.7615977834088159)),
 (1784, np.float64(0.7615977150705628)),
 (2578, np.float64(0.7615976778191441)),
 (150, np.float64(0.7615976453752452)),
 (3724, np.float64(0.7615975951237102)),
 (1013, np.float64(0.761597590729192)),
 (4211, np.float64(0.7615975631290405)),
 (1213, np.float64(0.7615975380289366)),
 (1345, np.float64(0.7615974549075267)),
 (312, np.float64(0.7615974086679764)),
 (4039, np.float64(0.7615973645677722)),
 (2967, np.float64(0.7615973512232982)),
 (614, np.float64(0.7615972949789032)),
 (281, np.float64(0.7615972537743877)),
 (174, np.float64(0.7615972462403858)),
 (3493, np.float64(0.7615971922075141)),
 (3624, np.float64(0.7615971821325882)),
 (972, np.float64(0.7615971791001622)),
 (1274, np.float64(0.7615971587672579)),
 (1959, np.float64(0.76159713681488)),
 (3970, np.float64(0.7615971093895815)),
 (2767, np.float64(0.761597036725786)),
 (2684, np.float64(0.7615969580667049)),
 (1633, np.float64(0.7615969212804632)),
 (1301, np.float64(0.7615969152876747)),
 (2614, np.float64(0.7615968705847304)),
 (404, np.float64(0.7615968645009663)),
 (31, np.float64(0.7615968611459102)),
 (236, np.float64(0.7615968500250061)),
 (3458, np.float64(0.7615968368133123)),
 (45, np.float64(0.7615968356260667)),
 (3710, np.float64(0.7615968336157509)),
 (2875, np.float64(0.7615968231470857)),
 (2218, np.float64(0.7615967945108832)),
 (3618, np.float64(0.7615967885212445)),
 (83, np.float64(0.7615967883763904)),
 (74, np.float64(0.7615967723180396)),
 (3197, np.float64(0.7615967399388174)),
 (823, np.float64(0.7615967328804691)),
 (1653, np.float64(0.7615967172013711)),
 (2636, np.float64(0.7615967096350685)),
 (3948, np.float64(0.7615966992621497)),
 (1914, np.float64(0.7615966890083938)),
 (646, np.float64(0.7615966462055832)),
 (2616, np.float64(0.761596630455851)),
 (68, np.float64(0.7615966221144029)),
 (985, np.float64(0.7615966157835751)),
 (2645, np.float64(0.7615966055095773)),
 (1843, np.float64(0.7615966043001626)),
 (3695, np.float64(0.7615965902654382)),
 (2990, np.float64(0.7615965764296699)),
 (1547, np.float64(0.7615965590191865)),
 (568, np.float64(0.7615965460568768)),
 (1513, np.float64(0.7615965325364586)),
 (2964, np.float64(0.7615965266453545)),
 (2626, np.float64(0.7615965113295541)),
 (369, np.float64(0.7615964896274535)),
 (582, np.float64(0.76159648058496)),
 (1644, np.float64(0.7615964795441176)),
 (2509, np.float64(0.7615964690840862)),
 (3302, np.float64(0.7615964585308395)),
 (4754, np.float64(0.7615964501791365)),
 (1528, np.float64(0.761596447467693)),
 (2132, np.float64(0.7615964436553664)),
 (2424, np.float64(0.7615964406323861)),
 (3336, np.float64(0.7615964348441581)),
 (951, np.float64(0.7615964250748417)),
 (1482, np.float64(0.7615964106539647)),
 (617, np.float64(0.761596406221536)),
 (2721, np.float64(0.7615963786889532)),
 (1318, np.float64(0.7615963718038168)),
 (1198, np.float64(0.7615963702530129)),
 (1016, np.float64(0.7615963620338443)),
 (1199, np.float64(0.7615963513746319)),
 (2327, np.float64(0.7615963441297169)),
 (1034, np.float64(0.7615963350053945)),
 (507, np.float64(0.7615963324920871)),
 (3297, np.float64(0.7615963118870559)),
 (1782, np.float64(0.761596310352704)),
 (2193, np.float64(0.761596302979706)),
 (1802, np.float64(0.7615963024132535)),
 (4328, np.float64(0.7615962730691883)),
 (557, np.float64(0.761596270334538)),
 (871, np.float64(0.7615962643998974)),
 (27, np.float64(0.7615962614863476)),
 (1796, np.float64(0.7615962372612116)),
 (1158, np.float64(0.7615962236331606)),
 (4301, np.float64(0.7615962230528673)),
 (3747, np.float64(0.7615962161411881)),
 (3104, np.float64(0.7615962111727139)),
 (3419, np.float64(0.7615962081742197)),
 (199, np.float64(0.7615962052623532)),
 (1438, np.float64(0.7615962049464748)),
 (4176, np.float64(0.7615962046187057)),
 (3172, np.float64(0.7615961995343827)),
 (894, np.float64(0.7615961932431303)),
 (3306, np.float64(0.7615961833344875)),
 (107, np.float64(0.7615961825685534)),
 (2781, np.float64(0.7615961724986344)),
 (2016, np.float64(0.7615961701429629)),
 (475, np.float64(0.7615961662967079)),
 (1163, np.float64(0.7615961619484165)),
 (2370, np.float64(0.7615961462445648)),
 (2382, np.float64(0.761596141403482)),
 (2951, np.float64(0.7615961413034433)),
 (513, np.float64(0.7615961349694704)),
 (1434, np.float64(0.7615961313182579)),
 (3396, np.float64(0.7615961219459797)),
 (275, np.float64(0.7615961151373294)),
 (2726, np.float64(0.7615961124020405)),
 (1275, np.float64(0.7615961066064791)),
 (1763, np.float64(0.7615961035526871)),
 (483, np.float64(0.7615960970517173)),
 (149, np.float64(0.7615960862025788)),
 (4796, np.float64(0.7615960836667319)),
 (2008, np.float64(0.7615960735241115)),
 (2194, np.float64(0.7615960675898116)),
 (539, np.float64(0.761596063532791)),
 (2226, np.float64(0.7615960480913639)),
 (3312, np.float64(0.7615960422663446)),
 (2878, np.float64(0.7615960403927213)),
 (2543, np.float64(0.761596032426156)),
 (2658, np.float64(0.7615960295408036)),
 (1967, np.float64(0.7615960276252545)),
 (2808, np.float64(0.7615960203572876)),
 (140, np.float64(0.7615960140942014)),
 (4263, np.float64(0.7615959902138616)),
 (626, np.float64(0.7615959863227991)),
 (1735, np.float64(0.7615959858991482)),
 (1649, np.float64(0.761595980595608)),
 (4313, np.float64(0.761595979942069)),
 (1172, np.float64(0.7615959722106687)),
 (3087, np.float64(0.7615959583151494)),
 (4187, np.float64(0.761595957327229)),
 (1068, np.float64(0.7615959556411613)),
 (4591, np.float64(0.7615959526350706)),
 (535, np.float64(0.7615959389696446)),
 (3656, np.float64(0.7615959292550617)),
 (4042, np.float64(0.7615959228348653)),
 (1491, np.float64(0.7615959205776683)),
 (835, np.float64(0.7615959167296565)),
 (1817, np.float64(0.7615959147622464)),
 (373, np.float64(0.7615959112351297)),
 (7, np.float64(0.7615959082558289)),
 (495, np.float64(0.7615959077398222)),
 (2920, np.float64(0.7615958955293085)),
 (3908, np.float64(0.7615958928063163)),
 (1402, np.float64(0.7615958891308412)),
 (467, np.float64(0.7615958854985239)),
 (1840, np.float64(0.7615958798009628)),
 (148, np.float64(0.7615958735601294)),
 (4617, np.float64(0.7615958620546315)),
 (4637, np.float64(0.7615958608129583)),
 (3098, np.float64(0.7615958554750063)),
 (1020, np.float64(0.7615958551026051)),
 (946, np.float64(0.7615958544232942)),
 (1471, np.float64(0.7615958539351693)),
 (4481, np.float64(0.7615958436513673)),
 (3221, np.float64(0.761595842818922)),
 (487, np.float64(0.7615958353288594)),
 (3105, np.float64(0.7615958337621579)),
 (1118, np.float64(0.7615958284233005)),
 (4119, np.float64(0.7615958270827309)),
 (2051, np.float64(0.761595817930377)),
 (2797, np.float64(0.7615958116585578)),
 (1285, np.float64(0.761595811415304)),
 (3833, np.float64(0.7615958097048062)),
 (4106, np.float64(0.7615958073230646)),
 (3643, np.float64(0.761595806874458)),
 (2529, np.float64(0.7615957958601608)),
 (1414, np.float64(0.7615957896026136)),
 (1467, np.float64(0.7615957883648113)),
 (3068, np.float64(0.7615957793561751)),
 (1188, np.float64(0.7615957742780365)),
 (1326, np.float64(0.7615957622581778)),
 (3191, np.float64(0.7615957551938376)),
 (4649, np.float64(0.7615957529960979)),
 (1279, np.float64(0.7615957520187707)),
 (581, np.float64(0.7615957500533548)),
 (1920, np.float64(0.7615957420996305)),
 (466, np.float64(0.7615957382108943)),
 (4347, np.float64(0.76159573443516)),
 (3789, np.float64(0.7615957331067633)),
 (2142, np.float64(0.761595731658543)),
 (26, np.float64(0.7615957270499999)),
 (2863, np.float64(0.7615957214453891)),
 (3364, np.float64(0.7615957055120943)),
 (365, np.float64(0.7615957039636813)),
 (1067, np.float64(0.7615957016882067)),
 (1004, np.float64(0.7615957013105062)),
 (2724, np.float64(0.761595698410556)),
 (1042, np.float64(0.7615956978702519)),
 (672, np.float64(0.7615956863389556)),
 (3501, np.float64(0.7615956826289981)),
 (4038, np.float64(0.7615956810155007)),
 (1272, np.float64(0.7615956792437858)),
 (2874, np.float64(0.761595670419504)),
 (4376, np.float64(0.761595666696288)),
 (3626, np.float64(0.7615956660025908)),
 (1665, np.float64(0.7615956590208625)),
 (1175, np.float64(0.7615956484831755)),
 (1449, np.float64(0.7615956474056027)),
 (4045, np.float64(0.7615956466827106)),
 (2496, np.float64(0.7615956452633327)),
 (91, np.float64(0.7615956252645399)),
 (549, np.float64(0.7615956187584139)),
 (2876, np.float64(0.7615956128678067)),
 (47, np.float64(0.7615956092492897)),
 (2408, np.float64(0.7615956011715098)),
 (1246, np.float64(0.7615956002475194)),
 (3776, np.float64(0.7615955969040771)),
 (1106, np.float64(0.7615955963775505)),
 (134, np.float64(0.7615955880317454)),
 (2011, np.float64(0.7615955767906889)),
 (875, np.float64(0.7615955704967177)),
 (3004, np.float64(0.7615955521224492)),
 (4074, np.float64(0.7615955470189494)),
 (1271, np.float64(0.7615955412839144)),
 (1201, np.float64(0.7615955399337271)),
 (2403, np.float64(0.7615955393219234)),
 (461, np.float64(0.7615955387864148)),
 (4630, np.float64(0.7615955378638112)),
 (637, np.float64(0.7615955343629388)),
 (3498, np.float64(0.7615955335970253)),
 (692, np.float64(0.7615955212246822)),
 (3516, np.float64(0.7615955099962873)),
 (3249, np.float64(0.761595500190574)),
 (4795, np.float64(0.7615954969382003)),
 (3018, np.float64(0.7615954964134793)),
 (1298, np.float64(0.7615954961543411)),
 (1377, np.float64(0.7615954849276608)),
 (1463, np.float64(0.761595483005442)),
 (2314, np.float64(0.7615954805169421)),
 (3570, np.float64(0.7615954780040386)),
 (430, np.float64(0.7615954676012812)),
 (454, np.float64(0.7615954522871337)),
 (313, np.float64(0.7615954497728964)),
 (1753, np.float64(0.7615954452402446)),
 (1834, np.float64(0.7615954434948256)),
 (2541, np.float64(0.7615954408354725)),
 (3161, np.float64(0.7615954352860403)),
 (3616, np.float64(0.7615954320917674)),
 (1117, np.float64(0.7615954301401917)),
 (2789, np.float64(0.7615954171660431)),
 (1741, np.float64(0.761595413601749)),
 (3993, np.float64(0.7615954095782399)),
 (2859, np.float64(0.761595409064826)),
 (2048, np.float64(0.7615954089977912)),
 (473, np.float64(0.761595405934126)),
 (2599, np.float64(0.7615954007719876)),
 (2024, np.float64(0.7615953984796638)),
 (3971, np.float64(0.7615953916837572)),
 (1939, np.float64(0.7615953901726965)),
 (3931, np.float64(0.7615953855973717)),
 (1217, np.float64(0.7615953838297801)),
 (1529, np.float64(0.7615953831170356)),
 (2220, np.float64(0.7615953803215347)),
 (4629, np.float64(0.7615953794353282)),
 (3944, np.float64(0.7615953769130631)),
 (785, np.float64(0.7615953741861671)),
 (1532, np.float64(0.7615953626119548)),
 (1594, np.float64(0.7615953615734089)),
 (632, np.float64(0.7615953596104864)),
 (2250, np.float64(0.7615953582783055)),
 (595, np.float64(0.7615953576782465)),
 (3195, np.float64(0.7615953492567699)),
 (184, np.float64(0.7615953481107822)),
 (1957, np.float64(0.7615953384501055)),
 (4288, np.float64(0.7615953362579579)),
 (1606, np.float64(0.7615953356310305)),
 (3325, np.float64(0.7615953334743915)),
 (1278, np.float64(0.7615953327848498)),
 (1999, np.float64(0.761595331239207)),
 (2735, np.float64(0.7615953309286096)),
 (488, np.float64(0.7615953277870893)),
 (137, np.float64(0.761595326578796)),
 (2664, np.float64(0.7615953188049024)),
 (1412, np.float64(0.7615953152916949)),
 (1012, np.float64(0.7615953144630879)),
 (127, np.float64(0.7615953123184828)),
 (5, np.float64(0.761595309447695)),
 (502, np.float64(0.7615953093747632)),
 (3351, np.float64(0.7615953066168331)),
 (3723, np.float64(0.7615953005308976)),
 (1365, np.float64(0.7615952993551569)),
 (1053, np.float64(0.7615952989035613)),
 (2229, np.float64(0.7615952972256338)),
 (29, np.float64(0.7615952950243241)),
 (2081, np.float64(0.7615952924908794)),
 (432, np.float64(0.7615952882416198)),
 (4323, np.float64(0.7615952880156523)),
 (3158, np.float64(0.7615952835759738)),
 (307, np.float64(0.7615952804876563)),
 (2819, np.float64(0.76159527763601)),
 (2109, np.float64(0.761595277014876)),
 (899, np.float64(0.761595276606759)),
 (3294, np.float64(0.7615952764436014)),
 (4273, np.float64(0.7615952748403099)),
 (838, np.float64(0.7615952746289849)),
 (2583, np.float64(0.7615952671427818)),
 (1138, np.float64(0.7615952642394306)),
 (4057, np.float64(0.7615952564410949)),
 (3096, np.float64(0.7615952452255532)),
 (854, np.float64(0.7615952448832549)),
 (2687, np.float64(0.7615952351835795)),
 (787, np.float64(0.7615952344949994)),
 (87, np.float64(0.761595231797112)),
 (2366, np.float64(0.7615952245115621)),
 (4654, np.float64(0.7615952218978104)),
 (2550, np.float64(0.7615952155522603)),
 (342, np.float64(0.7615952152455906)),
 (2258, np.float64(0.7615952126679291)),
 (1319, np.float64(0.7615952090696729)),
 (270, np.float64(0.7615952054473224)),
 (3729, np.float64(0.7615951940993019)),
 (3666, np.float64(0.7615951921219657)),
 (3439, np.float64(0.7615951903375019)),
 (1395, np.float64(0.7615951882271891)),
 (2646, np.float64(0.7615951838611853)),
 (3556, np.float64(0.7615951832822658)),
 (4542, np.float64(0.7615951810059708)),
 (782, np.float64(0.7615951762934522)),
 (2066, np.float64(0.7615951759016175)),
 (3386, np.float64(0.7615951750672019)),
 (883, np.float64(0.7615951732492062)),
 (999, np.float64(0.7615951729299392)),
 (139, np.float64(0.7615951677609403)),
 (3804, np.float64(0.7615951631377954)),
 (1912, np.float64(0.7615951623049719)),
 (372, np.float64(0.7615951620505399)),
 (2812, np.float64(0.7615951611325391)),
 (43, np.float64(0.7615951605621958)),
 (420, np.float64(0.7615951598824612)),
 (758, np.float64(0.7615951587590225)),
 (3945, np.float64(0.7615951584070189)),
 (2936, np.float64(0.7615951573425557)),
 (3534, np.float64(0.7615951548964498)),
 (1506, np.float64(0.7615951540514521)),
 (4550, np.float64(0.7615951537244618)),
 (131, np.float64(0.7615951488377541)),
 (901, np.float64(0.7615951444491607)),
 (1678, np.float64(0.7615951443916906)),
 (2358, np.float64(0.761595142781675)),
 (1727, np.float64(0.7615951425080614)),
 (2198, np.float64(0.7615951362142358)),
 (4260, np.float64(0.7615951277601815)),
 (635, np.float64(0.7615951276185713)),
 (3, np.float64(0.761595125164868)),
 (1672, np.float64(0.7615951076212361)),
 (1822, np.float64(0.7615950995949827)),
 (1555, np.float64(0.7615950935365604)),
 (804, np.float64(0.7615950920287867)),
 (2361, np.float64(0.7615950913486488)),
 (301, np.float64(0.7615950884567831)),
 (3427, np.float64(0.7615950878297634)),
 (3657, np.float64(0.7615950871358145)),
 (11, np.float64(0.7615950846887262)),
 (213, np.float64(0.7615950754392553)),
 (1302, np.float64(0.7615950694032828)),
 (2644, np.float64(0.7615950596712606)),
 (794, np.float64(0.7615950559459232)),
 (228, np.float64(0.7615950507590916)),
 (170, np.float64(0.7615950493264175)),
 (1525, np.float64(0.7615950380616656)),
 (412, np.float64(0.761595035641606)),
 (2427, np.float64(0.7615950241887295)),
 (2704, np.float64(0.7615950236006119)),
 (2482, np.float64(0.7615950163701279)),
 (588, np.float64(0.7615950131696787)),
 (1531, np.float64(0.7615950073711654)),
 (4007, np.float64(0.7615950044800589)),
 (1473, np.float64(0.7615949997409787)),
 (1354, np.float64(0.7615949981428141)),
 (790, np.float64(0.7615949701479091)),
 (596, np.float64(0.761594969131122)),
 (456, np.float64(0.7615949680610103)),
 (2197, np.float64(0.7615949655218833)),
 (1986, np.float64(0.761594950242256)),
 (1737, np.float64(0.7615949450731618)),
 (4653, np.float64(0.7615949412624051)),
 (4526, np.float64(0.7615949410289924)),
 (239, np.float64(0.7615949408708028)),
 (206, np.float64(0.7615949388600166)),
 (277, np.float64(0.7615949380241562)),
 (2147, np.float64(0.7615949343756594)),
 (2160, np.float64(0.7615949265071629)),
 (222, np.float64(0.7615949099392512)),
 (406, np.float64(0.7615949063096705)),
 (1892, np.float64(0.7615948980032944)),
 (343, np.float64(0.7615948878029238)),
 (1779, np.float64(0.761594879105044)),
 (153, np.float64(0.7615948772042955)),
 (89, np.float64(0.7615948693628938)),
 (102, np.float64(0.7615948376670457)),
 (4679, np.float64(0.761594832065701)),
 (230, np.float64(0.7615947977901872)),
 (3505, np.float64(0.7615947800802892)),
 (2043, np.float64(0.7615947755890162)),
 (4326, np.float64(0.7615947746144665)),
 (2144, np.float64(0.76159476767346)),
 (3550, np.float64(0.7615947664705865)),
 (599, np.float64(0.7615947621078898)),
 (1, np.float64(0.7615941559557649)),
 (2, np.float64(0.7615941559557649)),
 (4, np.float64(0.7615941559557649)),
 (6, np.float64(0.7615941559557649)),
 (8, np.float64(0.7615941559557649)),
 (9, np.float64(0.7615941559557649)),
 (10, np.float64(0.7615941559557649)),
 (12, np.float64(0.7615941559557649)),
 (13, np.float64(0.7615941559557649)),
 (14, np.float64(0.7615941559557649)),
 (15, np.float64(0.7615941559557649)),
 (16, np.float64(0.7615941559557649)),
 (17, np.float64(0.7615941559557649)),
 (18, np.float64(0.7615941559557649)),
 (19, np.float64(0.7615941559557649)),
 (20, np.float64(0.7615941559557649)),
 (21, np.float64(0.7615941559557649)),
 (22, np.float64(0.7615941559557649)),
 (23, np.float64(0.7615941559557649)),
 (24, np.float64(0.7615941559557649)),
 (25, np.float64(0.7615941559557649)),
 (28, np.float64(0.7615941559557649)),
 (30, np.float64(0.7615941559557649)),
 (32, np.float64(0.7615941559557649)),
 (33, np.float64(0.7615941559557649)),
 (34, np.float64(0.7615941559557649)),
 (35, np.float64(0.7615941559557649)),
 (37, np.float64(0.7615941559557649)),
 (38, np.float64(0.7615941559557649)),
 (39, np.float64(0.7615941559557649)),
 (40, np.float64(0.7615941559557649)),
 (41, np.float64(0.7615941559557649)),
 (42, np.float64(0.7615941559557649)),
 (44, np.float64(0.7615941559557649)),
 (46, np.float64(0.7615941559557649)),
 (48, np.float64(0.7615941559557649)),
 (49, np.float64(0.7615941559557649)),
 (50, np.float64(0.7615941559557649)),
 (51, np.float64(0.7615941559557649)),
 (52, np.float64(0.7615941559557649)),
 (53, np.float64(0.7615941559557649)),
 (54, np.float64(0.7615941559557649)),
 (55, np.float64(0.7615941559557649)),
 (56, np.float64(0.7615941559557649)),
 (57, np.float64(0.7615941559557649)),
 (58, np.float64(0.7615941559557649)),
 (59, np.float64(0.7615941559557649)),
 (60, np.float64(0.7615941559557649)),
 (61, np.float64(0.7615941559557649)),
 (62, np.float64(0.7615941559557649)),
 (63, np.float64(0.7615941559557649)),
 (64, np.float64(0.7615941559557649)),
 (65, np.float64(0.7615941559557649)),
 (66, np.float64(0.7615941559557649)),
 (67, np.float64(0.7615941559557649)),
 (69, np.float64(0.7615941559557649)),
 (70, np.float64(0.7615941559557649)),
 (71, np.float64(0.7615941559557649)),
 (72, np.float64(0.7615941559557649)),
 (73, np.float64(0.7615941559557649)),
 (75, np.float64(0.7615941559557649)),
 (76, np.float64(0.7615941559557649)),
 (77, np.float64(0.7615941559557649)),
 (78, np.float64(0.7615941559557649)),
 (79, np.float64(0.7615941559557649)),
 (80, np.float64(0.7615941559557649)),
 (81, np.float64(0.7615941559557649)),
 (82, np.float64(0.7615941559557649)),
 (84, np.float64(0.7615941559557649)),
 (85, np.float64(0.7615941559557649)),
 (86, np.float64(0.7615941559557649)),
 (88, np.float64(0.7615941559557649)),
 (90, np.float64(0.7615941559557649)),
 (92, np.float64(0.7615941559557649)),
 (93, np.float64(0.7615941559557649)),
 (94, np.float64(0.7615941559557649)),
 (95, np.float64(0.7615941559557649)),
 (96, np.float64(0.7615941559557649)),

In [65]:
sigma_scores[1:11]

[(1341, np.float64(0.7616030155858681)),
 (634, np.float64(0.7616028561141562)),
 (3604, np.float64(0.761601930611584)),
 (2130, np.float64(0.7616015339622925)),
 (775, np.float64(0.7616011086528326)),
 (529, np.float64(0.7615996114069044)),
 (151, np.float64(0.7615991171152051)),
 (311, np.float64(0.7615990624497703)),
 (847, np.float64(0.7615987706430224)),
 (570, np.float64(0.7615986450599548))]

In [66]:
# to access index of above list

ind=[index[0] for index in sigma_scores[1:11]]
ind

[1341, 634, 3604, 2130, 775, 529, 151, 311, 847, 570]

In [67]:
data['original_title'].iloc[ind]

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [68]:
#define function that will give recommendations

def give_rec(title,model):

    idx=indices[title]

    model_scores=list(enumerate(list(model[indices[idx]])))

    model_scores=sorted(model_scores,key=lambda x:x[1],reverse=True)

    model_scores=model_scores[1:11]

    movie_indices=[index[0] for index in model_scores]

    return data['original_title'].iloc[movie_indices]

In [69]:
# Testing our content-based recommendation system with the film 'Avatar'

give_rec('Avatar',sig)

C:\Users\FARHAD\AppData\Local\Temp\ipykernel_14560\371111120.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model_scores=list(enumerate(list(model[indices[idx]])))

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

### Improve Existing Content Based Recommender System

In [70]:
data.columns

Index(['Unnamed: 0', 'budget', 'genres', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'tagline',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

In [71]:
from ast import literal_eval

In [72]:
# Parse the stringified features into their corresponding python objects

features=['cast','crew','keywords','genres']

In [73]:
for feature in features:
    data[feature]=data[feature].apply(literal_eval)

In [74]:
data['crew'][1]

[{'credit_id': '52fe4232c3a36847f800b579',
  'department': 'Camera',
  'gender': 2,
  'id': 120,
  'job': 'Director of Photography',
  'name': 'Dariusz Wolski'},
 {'credit_id': '52fe4232c3a36847f800b4fd',
  'department': 'Directing',
  'gender': 2,
  'id': 1704,
  'job': 'Director',
  'name': 'Gore Verbinski'},
 {'credit_id': '52fe4232c3a36847f800b54f',
  'department': 'Production',
  'gender': 2,
  'id': 770,
  'job': 'Producer',
  'name': 'Jerry Bruckheimer'},
 {'credit_id': '52fe4232c3a36847f800b503',
  'department': 'Writing',
  'gender': 2,
  'id': 1705,
  'job': 'Screenplay',
  'name': 'Ted Elliott'},
 {'credit_id': '52fe4232c3a36847f800b509',
  'department': 'Writing',
  'gender': 2,
  'id': 1706,
  'job': 'Screenplay',
  'name': 'Terry Rossio'},
 {'credit_id': '52fe4232c3a36847f800b57f',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '52fe4232c3a36847f800b585',
  'department': 'Editing',
  'gender': 2,
  'id': 1722,
  'job': 'Editor',
  'name': 'Craig Wood'},
 {'credit_id': '52fe4232c3a36847f800b573',
  'department': 'Sound',
  'gender': 2,
  'id': 947,
  'job': 'Original Music Composer',
  'name': 'Hans Zimmer'},
 {'credit_id': '52fe4232c3a36847f800b555',
  'department': 'Production',
  'gender': 2,
  'id': 2444,
  'job': 'Executive Producer',
  'name': 'Mike Stenson'},
 {'credit_id': '52fe4232c3a36847f800b561',
  'department': 'Production',
  'gender': 2,
  'id': 2445,
  'job': 'Producer',
  'name': 'Eric McLeod'},
 {'credit_id': '52fe4232c3a36847f800b55b',
  'department': 'Production',
  'gender': 2,
  'id': 2446,
  'job': 'Producer',
  'name': 'Chad Oman'},
 {'credit_id': '52fe4232c3a36847f800b567',
  'department': 'Production',
  'gender': 0,
  'id': 2447,
  'job': 'Producer',
  'name': 'Peter Kohn'},
 {'credit_id': '52fe4232c3a36847f800b56d',
  'department': 'Production',
  'gender': 0,
  'id': 2448,
  'job': 'Producer',
  'name': 'Pat Sandston'},
 {'credit_id': '52fe4232c3a36847f800b58b',
  'department': 'Production',
  'gender': 1,
  'id': 2215,
  'job': 'Casting',
  'name': 'Denise Chamian'},
 {'credit_id': '52fe4232c3a36847f800b597',
  'department': 'Art',
  'gender': 2,
  'id': 1226,
  'job': 'Production Design',
  'name': 'Rick Heinrichs'},
 {'credit_id': '52fe4232c3a36847f800b59d',
  'department': 'Art',
  'gender': 2,
  'id': 553,
  'job': 'Art Direction',
  'name': 'John Dexter'},
 {'credit_id': '52fe4232c3a36847f800b591',
  'department': 'Production',
  'gender': 1,
  'id': 3311,
  'job': 'Casting',
  'name': 'Priscilla John'},
 {'credit_id': '52fe4232c3a36847f800b5a3',
  'department': 'Art',
  'gender': 1,
  'id': 4032,
  'job': 'Set Decoration',
  'name': 'Cheryl Carasik'},
 {'credit_id': '52fe4232c3a36847f800b5a9',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 4033,
  'job': 'Costume Design',
  'name': 'Liz Dann'},
 {'credit_id': '52fe4232c3a36847f800b5af',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 4034,
  'job': 'Costume Design',
  'name': 'Penny Rose'},
 {'credit_id': '56427ce8c3a3686a53000d8b',
  'department': 'Sound',
  'gender': 2,
  'id': 5132,
  'job': 'Music Supervisor',
  'name': 'Bob Badami'},
 {'credit_id': '55993c15c3a36855db002f33',
  'department': 'Art',
  'gender': 2,
  'id': 146439,
  'job': 'Conceptual Design',
  'name': 'James Ward Byrkit'},
 {'credit_id': '52fe4232c3a36847f800b5b9',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 406204,
  'job': 'Makeup Department Head',
  'name': 'Ve Neill'},
 {'credit_id': '56e47f7892514132690017bd',
  'department': 'Crew',
  'gender': 2,
  'id': 1259516,
  'job': 'Stunts',
  'name': 'John Dixon'},
 {'credit_id': '5740be639251416597000849',
  'department': 'Crew',
  'gender': 0,
  'id': 1336716,
  'job': 'CGI Supervisor',
  'name': 'Dottie Starling'},
 {'credit_id': '56427c639251412fc8000dc1',
  'department': 'Directing',
  'gender': 1,
  'id': 1344278,
  'job': 'Script Supervisor',
  'name': 'Pamela Alch'},
 {'credit_id': '57083101c3a3681d320004e6',
  'department': 'Crew',
  'gender': 0,
  'id': 1368867,
  'job': 'Special Effects Coordinator',
  'name': 'Allen Hall'},
 {'credit_id': '56427d5ec3a3686a62000d4a',
  'department': 'Sound',
  'gender': 0,
  'id': 1368884,
  'job': 'Music Editor',
  'name': 'Melissa Muik'},
 {'credit_id': '56427c7b9251412fd4000e07',
  'department': 'Directing',
  'gender': 1,
  'id': 1395290,
  'job': 'Script Supervisor',
  'name': 'Sharron Reynolds'},
 {'credit_id': '56427d2bc3a3686a53000d9b',
  'department': 'Sound',
  'gender': 0,
  'id': 1399327,
  'job': 'Music Editor',
  'name': 'Barbara McDermott'},
 {'credit_id': '56427cb4c3a3686a53000d87',
  'department': 'Directing',
  'gender': 1,
  'id': 1400738,
  'job': 'Script Supervisor',
  'name': 'Karen Golden'},
 {'credit_id': '56427d169251412fd4000e23',
  'department': 'Sound',
  'gender': 0,
  'id': 1534197,
  'job': 'Music Editor',
  'name': 'Katie Greathouse'}]

In [75]:
# Get the director's name from the crew feature. If director is not listed, return NaN

def get_director(x):
    for i in x:
        if i['job']=='Director':
            return i['name'].strip()

    else:
        return np.nan

In [76]:
get_director(data['crew'][0])

'James Cameron'

In [77]:
data['director']=data['crew'].apply(get_director)

In [78]:
data['director'].shape

(4803,)

In [79]:
data['director'].isnull().sum()

np.int64(30)

In [80]:
# Returns the list top 3 elements or entire list , whichever is more..
def get_list(x):
    names=[i['name'].strip().lower() for i in x if type(x)==list]

    if len(names)>3:
        return names[0:3]
    else:
        return names

In [81]:
get_list(data['crew'][0])

['stephen e. rivkin', 'rick carter', 'christopher boyes']

In [82]:
for feature in features:
    data[feature]=data[feature].apply(get_list)

In [83]:
data[features]

,cast,crew,keywords,genres
0,"[sam worthington, zoe saldana, sigourney weaver]","[stephen e. rivkin, rick carter, christopher boyes]","[culture clash, future, space war]","[action, adventure, fantasy]"
1,"[johnny depp, orlando bloom, keira knightley]","[dariusz wolski, gore verbinski, jerry bruckheimer]","[ocean, drug abuse, exotic island]","[adventure, fantasy, action]"
2,"[daniel craig, christoph waltz, léa seydoux]","[thomas newman, sam mendes, anna pinnock]","[spy, based on novel, secret agent]","[action, adventure, crime]"
3,"[christian bale, michael caine, gary oldman]","[hans zimmer, charles roven, christopher nolan]","[dc comics, crime fighter, terrorist]","[action, crime, drama]"
4,"[taylor kitsch, lynn collins, samantha morton]","[andrew stanton, andrew stanton, john lasseter]","[based on novel, mars, medallion]","[action, adventure, science fiction]"
...,...,...,...,...
4798,"[carlos gallardo, jaime de hoyos, peter marquardt]","[robert rodriguez, robert rodriguez, robert rodriguez]","[united states–mexico barrier, legs, arms]","[action, crime, thriller]"
4799,"[edward burns, kerry bishé, marsha dietlein]","[edward burns, edward burns, edward burns]",[],"[comedy, romance]"
4800,"[eric mabius, kristin booth, crystal lowe]","[carla hetland, harvey kahn, adam sliwinski]","[date, love at first sight, narration]","[comedy, drama, romance]"
4801,"[daniel henney, eliza coupe, bill paxton]","[daniel hsia, daniel hsia]",[],[]
4802,"[drew barrymore, brian herzlinger, corey feldman]","[clark peterson, andrew reimer, brian herzlinger]","[obsession, camcorder, crush]",[documentary]

In [84]:
data.dropna(subset=['director'],inplace=True)

In [86]:
data['cast'][0]

['sam worthington', 'zoe saldana', 'sigourney weaver']

In [87]:
' '.join(data['cast'][0])

'sam worthington zoe saldana sigourney weaver'

In [88]:
def create_feature(row):
    return ' '.join(row['keywords']) + ' ' + ' '.join(row['cast']) + ' ' + row['director'] + ' ' + ' '.join(row['genres'])

In [89]:
data['important_feature']=data.apply(create_feature,axis=1)

In [90]:
data.head(2)

,Unnamed: 0,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew,director,important_feature
0,0,237000000,"[action, adventure, fantasy]",19995,"[culture clash, future, space war]",en,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289}, {""name"": ""Twentieth Century Fox Film Corporation"", ""id"": 306}, {""name"": ""Dune Entertainment"", ""id"": 444}, {""name"": ""Lightstorm Entertainment"", ""id"": 574}]",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Enter the World of Pandora.,7.2,11800,"[sam worthington, zoe saldana, sigourney weaver]","[stephen e. rivkin, rick carter, christopher boyes]",James Cameron,culture clash future space war sam worthington zoe saldana sigourney weaver James Cameron action adventure fantasy
1,1,300000000,"[adventure, fantasy, action]",285,"[ocean, drug abuse, exotic island]",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""name"": ""Jerry Bruckheimer Films"", ""id"": 130}, {""name"": ""Second Mate Productions"", ""id"": 19936}]",...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[johnny depp, orlando bloom, keira knightley]","[dariusz wolski, gore verbinski, jerry bruckheimer]",Gore Verbinski,ocean drug abuse exotic island johnny depp orlando bloom keira knightley Gore Verbinski adventure fantasy action

In [91]:
# Import CountVectorizer and create the count matrix

from sklearn.feature_extraction.text import CountVectorizer

In [92]:
count=CountVectorizer(stop_words='english')

In [93]:
count_matrix=count.fit_transform(data['important_feature'])

In [94]:
count_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 66282 stored elements and shape (4773, 10750)>

In [95]:
count_matrix.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [96]:
# Compute the Cosine Similarity matrix based on the count_matrix

from sklearn.metrics.pairwise import cosine_similarity

In [97]:
cosine_sim2=cosine_similarity(count_matrix,count_matrix)

In [99]:
cosine_sim2[0]

array([1.    , 0.1875, 0.1875, ..., 0.    , 0.    , 0.    ])

In [100]:
give_rec('Tangled',cosine_sim2)

C:\Users\FARHAD\AppData\Local\Temp\ipykernel_14560\371111120.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model_scores=list(enumerate(list(model[indices[idx]])))

578     Alvin and the Chipmunks: The Squeakquel
1108                                  Pinocchio
1481                         The House of Magic
1857                            Rugrats Go Wild
42                                  Toy Story 3
390                          Hotel Transylvania
565                                     Shrek 2
899                                       Shrek
1695                                    Aladdin
3281                        The Secret of Kells
Name: original_title, dtype: object

In [101]:
give_rec('The Godfather',cosine_sim2)

C:\Users\FARHAD\AppData\Local\Temp\ipykernel_14560\371111120.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model_scores=list(enumerate(list(model[indices[idx]])))

867     The Godfather: Part III
2731     The Godfather: Part II
1525             Apocalypse Now
2792        Glengarry Glen Ross
1209              The Rainmaker
3012              The Outsiders
4209           The Conversation
2649          The Son of No One
1018            The Cotton Club
4124         This Thing of Ours
Name: original_title, dtype: object

In [102]:
give_rec('The Godfather',sig)

C:\Users\FARHAD\AppData\Local\Temp\ipykernel_14560\371111120.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model_scores=list(enumerate(list(model[indices[idx]])))

2731                             The Godfather: Part II
1873                                         Blood Ties
3730                                              Cargo
867                             The Godfather: Part III
3623                                               Made
3963                                 They Came Together
2464                             The Master of Disguise
2973    For Greater Glory - The True Story of Cristiada
2389                                        Renaissance
1475                                  Playing for Keeps
Name: original_title, dtype: object